[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lmsstat"
version = "0.0.1"
authors = [{ name = "Daehwan Kim", email = "kdh5358@snu.ac.kr" }]
dynamic = ["description"]
dependencies = [
    "pandas", "numpy", "scipy"
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"

[project.urls]
Source = "https://github.com/daehwankum12/LMSstat_python"